# Generated by Django 5.2.14 on 2026-06-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_3d', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price_per_gram',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
