# Generated by Django 5.2.14 on 2026-06-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_3d', '0003_alter_material_price_per_gram_alter_model3d_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model3d',
            name='author',
        ),
    ]
