# Generated by Django 5.2.14 on 2026-06-06 10:22

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_3d', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PROC', 'В обработке'), ('PAY', 'Ожидает оплаты'), ('COMP', 'Выполнен'), ('CANC', 'Отменен')], default='PAY', max_length=4)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_3d_name', models.CharField(max_length=255)),
                ('model_3d_image', models.ImageField(blank=True, null=True, upload_to='model_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_name', models.CharField(max_length=255)),
                ('color_name', models.CharField(blank=True, max_length=255, null=True)),
                ('color_hex_code', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('quantity', models.PositiveIntegerField()),
                ('scale', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models_3d.color')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models_3d.material')),
                ('model_3d', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models_3d.model3d')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
