# Generated by Django 5.2.14 on 2026-06-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_material_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROC', 'В обработке'), ('COMP', 'Выполнен'), ('CANC', 'Отменен')], default='PROC', max_length=4),
        ),
    ]
